config/routes.rb
DetentionSystem::Application.routes.draw do
  resources :detentions

  resources :students

  resources :teachers

  root 'detentions#index'

end

app/models/detention.rb
class Detention < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :student

  DetTime = Struct.new(:date, :time)

  validates_presence_of :teacher_id, :student_id, :reason,
  		:points, :parent_detention, :status
  validates_uniqueness_of :time, :scope => [:date, :student_id]

  validates :status, inclusion: {in: %w(set done rescheduled escalated)}

  validate :date_is_in_future?

  def self.upcoming_separated_by_datetime
    all_dets = Detention.where("date > ? AND status = ?", Time.now, 'set')
        .order(date: :asc, time: :desc)
    unique_det_times = all_dets.uniq.pluck(:date, :time)
    array = Array.new
    unique_det_times.each do |datetime|
      dt = DetTime.new(datetime[0], datetime[1])
      array << [dt].push(all_dets.where(date: dt[:date], time: dt[:time]).to_a)
    end
    array
  end

  def self.pen
    dets = Detention.where(date: nil)
  end

  def datetime_for_header
    "#{date.strftime('%A')} #{time} - #{date.strftime('%-d %b')}"
  end

  def datetime_for_id
    "#{date.strftime('%Y%-m%-d')}#{time}"
  end

  private
    def date_is_in_future?
      if self.date < Date.today
        errors.add(:date, 'must be in the future')
      end
    end
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :detentions

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :detentions
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/detentions_controller.rb
class DetentionsController < ApplicationController
  before_action :set_detention, only: [:show, :edit, :update, :destroy]

  # GET /detentions
  # GET /detentions.json
  def index
    @pen_detentions = Detention.pen
    @detentions = Detention.upcoming_separated_by_datetime
    @detention = Detention.new
  end

  # GET /detentions/1
  # GET /detentions/1.json
  def show
  end

  # GET /detentions/1/edit
  def edit
  end

  # POST /detentions
  # POST /detentions.json
  def create
    @detention = Detention.new(detention_params)
    @detention.status = "set"
    #TODO: Use logged-in teacher
    @detention.teacher_id = 1
    @detention.parent_detention = 0

    respond_to do |format|
      if @detention.save
        format.html { render :partial => "detention_row",
            :locals => {:detention_row => @detention} }
        # format.json { render action: 'show', status: :created, location: @detention }
      else
        format.json { render json: @detention.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /detentions/1
  # PATCH/PUT /detentions/1.json
  def update
    respond_to do |format|
      if @detention.update(detention_params)
        format.html { redirect_to @detention, notice: 'Detention was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @detention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detentions/1
  # DELETE /detentions/1.json
  def destroy
    @detention.destroy
    respond_to do |format|
      format.html { redirect_to detentions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detention
      @detention = Detention.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detention_params
      params.require(:detention).permit(:teacher_id, :student_id, :date, :time, :reason, :points, :parent_detention, :status, :additional_notes)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render action: 'show', status: :created, location: @student }
      else
        format.html { render action: 'new' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:email, :name)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render action: 'show', status: :created, location: @teacher }
      else
        format.html { render action: 'new' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :email, :group)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/detentions_helper.rb
module DetentionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/detentions/_content.html.haml
#content
  = render 'header'
  = render partial: "detention", collection: @detentions

app/views/detentions/_detention.html.haml
.detention
  .title
    =detention[1][0].datetime_for_header
    .button Register
  - if detention_counter == 0
    .detention-header
      .student-name Student
      .detention-reason Reason
      .points Points

  %ul.selector{:id => "#{detention[1][0].datetime_for_id}"}
    = render partial: "detention_row", collection: detention[1]

app/views/detentions/_detention_row.html.haml
%li
  .student-name
    .avatar
      .move
    .name= detention_row.student.name
  .detention-reason= detention_row.reason
  .points= detention_row.points
  .controls
    .button Edit

app/views/detentions/_form.html.haml
#add-detention-modal
  .overlay
    .modal-container
      .modal
        .modal-top
          Create Detention
          .modal-close &times;
        .modal-bottom
          = form_for(@detention, remote: true) do |f|
            .field
              =f.label :student
              =f.select(:student_id, Student.all.collect {|s| [s.name, s.id] })
            .field
              = f.label :date
              = f.date_select :date
            .field
              = f.label :time
              = f.text_field :time
            .field
              = f.label :reason
              = f.text_field :reason
            .field
              = f.label :points
              = f.number_field :points
            .field
              = f.label :additional_notes
              = f.text_area :additional_notes
            = f.submit
            .button.save-another
              Save and add another

app/views/detentions/_header.html.haml
%header
  %nav
    %ul
      %li
        %a Dashboard
      %li
        %a History
      %li
        %a Settings
  #create-detention.button Create detention

app/views/detentions/_pen_detention.html.haml
%li
  .student-name
    .avatar
      .move
    .name= pen_detention.student.name
  .controls
    .tag.low
      .tooltip{:class => pen_detention.status}= pen_detention.status
    .delete

app/views/detentions/_sidebar.html.haml
#sidebar
  .user
    .inner
      .user-avatar
      Rufus Fleary
  .title
    Holding Pen
    .edit Edit
  %ul
    = render partial: "pen_detention", collection: @pen_detentions
  #add-to-pen.button Add Student to Pen

app/views/detentions/edit.html.erb
<h1>Editing detention</h1>

<%= render 'form' %>

<%= link_to 'Show', @detention %> |
<%= link_to 'Back', detentions_path %>

app/views/detentions/index.html.haml
= render 'sidebar'
= render 'content'
= render 'form'

app/views/detentions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Teacher:</strong>
  <%= @detention.teacher %>
</p>

<p>
  <strong>Student:</strong>
  <%= @detention.student %>
</p>

<p>
  <strong>Date:</strong>
  <%= @detention.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @detention.time %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @detention.reason %>
</p>

<p>
  <strong>Points:</strong>
  <%= @detention.points %>
</p>

<p>
  <strong>Parent detention:</strong>
  <%= @detention.parent_detention %>
</p>

<p>
  <strong>Status:</strong>
  <%= @detention.status %>
</p>

<p>
  <strong>Additional notes:</strong>
  <%= @detention.additional_notes %>
</p>

<%= link_to 'Edit', edit_detention_path(@detention) %> |
<%= link_to 'Back', detentions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DetentionSystem</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
  %html
    %head
      %title Detentions
      = stylesheet_link_tag "reset", media: "all", "data-turbolinks-track" => true
      = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
      = javascript_include_tag "application", "data-turbolinks-track" => true
      = csrf_meta_tags
    %body
      = yield

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.email %></td>
        <td><%= student.name %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :group %><br>
    <%= f.text_field :group %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<h1>Listing teachers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Group</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.email %></td>
        <td><%= teacher.group %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @teacher.email %>
</p>

<p>
  <strong>Group:</strong>
  <%= @teacher.group %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>